version: '2'
services:
  modbussim:
    image: ghcr.io/inoa-io/modbus-simulator:0.1
    restart: on-failure
    build: .
    privileged: true
    environment:
      - MODBUS_INTERFACE=${MODBUS_INTERFACE}
    volumes:
      - /dev:/dev:rw
    ports:
      - "5002:5002"
