version: '2'
services:
  modbussim:
    image: ghcr.io/inoa-io/modbus-simulator:0.1
    restart: on-failure
    build: .
    privileged: true
    environment:
      - MODBUS_INTERFACE=/dev2${SLAVE_INTERFACE}
    volumes:
      - ${SOCAT_HOME}:/dev2:rw
      - /dev:/dev:rw
    ports:
      - "5002:5002"
    depends_on:
      - socat
  socat:
    image: ghcr.io/inoa-io/socat:0.1
    build: compose/socat
    privileged: true
    volumes:
      - ${SOCAT_HOME}:/dev2:rw
      - /dev:/dev:rw
    environment:
      - SLAVE_INTERFACE=/dev2${SLAVE_INTERFACE}
      - MASTER_INTERFACE=/dev2${MASTER_INTERFACE}
  modpoll:
    image: ghcr.io/inoa-io/modpoll:0.1
    build: compose/modpoll
    privileged: true
    volumes:
      - ${SOCAT_HOME}:/dev2:rw
      - /dev:/dev:rw
#    command:
#      - "modpoll -m rtu -d 3 -a 9 -b 9600 -o 4 -c 2 -t 4:hex -r 0x4001 /dev2${MASTER_INTERFACE}"