name: PullRequest

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - uses: actions/checkout@v2
      - name: build simulator docker image
        run: docker build . -t ghcr.io/inoa-io/modbus-simulator:${{ steps.prep.outputs.BUILD_ID }}
      - name: build socat docker image
        run: docker build . -t ghcr.io/inoa-io/socat:${{ steps.prep.outputs.BUILD_ID }}
      - name: build modpoll image
        run: docker build . -t ghcr.io/inoa-io/modpoll:${{ steps.prep.outputs.BUILD_ID }}